name: Build VM and VHDX
on: 
  workflow_dispatch:
jobs:
  Build-VM-VHDX:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/scripts/vm.sh
          cd $GITHUB_WORKSPACE/scripts
          az deployment sub create \
            --name arc-footprint-deployment \
            --location $LOCATION \
            --template-file ./main-image.bicep \
            --parameters   resourceGroupName="rg-vm-vhdx-arc-footprint-new" \
                            galleryName="igarcfootprint" \
                            imageDefinitionName="id-arc-footprint" \
                            imageVersion="latest" \