name: Build VHDX
on: 
  workflow_dispatch:
    inputs:
      location:
        description: 'Azure Resource Location'
        required: true
        default: 'eastus'
        type: choice
        options:
        - eastus
        - eastus2
        - westus
        - westeurope
      publisher:
        description: 'OS Image Publisher'
        type: string
        default: 'MicrosoftWindowsServer'
        required: true
      offer:
        description: 'OS Image Offer'
        type: string
        default: 'WindowsServer'
        required: true
      sku:
        description: 'OS Image Sku'
        type: string
        default: '2022-datacenter-g2'
        required: true
      version:
        description: 'OS Image Version'
        type: string
        default: 'latest'
        required: true
      architecture:
        description: 'OS Image Architecture'
        type: string
        default: 'x64'
        required: true
      vmSize:
        description: 'VM Size'
        type: string
        default: 'Standard_D8s_v5'
        required: true
      computeGallery:
        description: 'Azure Compute Gallery Name'
        type: string
        default: footprintgallery
        required: true
      resourceGroup:
        description: 'Azure Resource Group'
        type: string
        default: footgrint-rg
        required: true

jobs:
  Build-VHDX:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
    - name: Run az deploy
      uses: azure/CLI@v1
      with:
        inlineScript: |
          #! /bin/bash

          GALLERY="${{ inputs.computeGallery }}"
          RG="${{ inputs.resourceGroup }}"
          GALLERY_EXISTS=false
          IDENTITY_EXISTS=false

          echo "Checking if things exists..."

          if [ -n "$(az sig show --gallery-name $GALLERY -g $RG --query id -o tsv 2>/dev/null)" ]; then
            echo "Gallery $GALLERY found in $RG. Use existing..."
            GALLERY_EXISTS=true
          fi

          if [ -n "$(az identity show -n ${{ inputs.computeGallery }}-identity -g $RG --query id -o tsv 2>/dev/null)" ]; then
            echo "Identity ${{ inputs.computeGallery }}-identity found in $RG. Use existing..."
            IDENTITY_EXISTS=true
          fi     

          echo "Running az deployment sub create..."

          az deployment sub create \
          --name fpdeployment${{github.run_id}} \
          --location ${{ inputs.location }} \
          --template-file $GITHUB_WORKSPACE/scripts/main-image.bicep \
          --parameters spClientId=${{ secrets.AZURE_CLIENT_ID }} \
                        spClientSecret=${{ secrets.AZURE_CLIENT_SECRET }} \
                        resourceGroupName=${{ inputs.resourceGroup }} \
                        galleryName=${{ inputs.computeGallery }} \
                        imageDefinitionName="WinServer" \
                        imageTemplateName="aksEEAIO-${{github.run_id}}" \
                        imageVersion="latest" \
                        publisher=${{ inputs.publisher }} \
                        offer=${{ inputs.offer }} \
                        sku=${{ inputs.sku }} \
                        version=${{ inputs.version }}\
                        architecture=${{ inputs.architecture }} \
                        vmSize=${{ inputs.vmSize }} \
                        exists=$GALLERY_EXISTS \
                        identityExists=$IDENTITY_EXISTS --debug