name: Build VM and VHDX
on: 
  workflow_dispatch:
    inputs:
      location:
        description: 'Azure Resource Location'
        required: true
        default: 'eastus'
        type: choice
        options:
        - eastus
        - eastus2
        - westus
        - westeurope
      publisher:
        description: 'OS Image Publisher'
        type: string
        default: 'MicrosoftWindowsServer'
        required: true
      offer:
        description: 'OS Image Offer'
        type: string
        default: 'WindowsServer'
        required: true
      sku:
        description: 'OS Image Sku'
        type: string
        default: '2022-datacenter-g2'
        required: true
      version:
        description: 'OS Image Version'
        type: string
        default: 'latest'
        required: true
      architecture:
        description: 'OS Image Architecture'
        type: string
        default: 'x64'
        required: true
      vmSize:
        description: 'VM Size'
        type: string
        default: 'Standard_D4s_v5'
        required: true
jobs:
  Build-VM-VHDX:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment sub create \
          --name arc-footprint-deployment \
          --location ${{ inputs.location }} \
          --template-file $GITHUB_WORKSPACE/scripts/main-image.bicep \
          --parameters applicationName="vm-vhdx-arc-footprint" \
                        galleryName="igarcfootprint" \
                        imageDefinitionName="id-arc-footprint" \
                        imageBuilderName="arc-footprint-image" \
                        imageVersion="latest" \
                        publisher=${{ inputs.publisher }} \
                        offer=${{ inputs.offer }} \
                        sku=${{ inputs.sku }} \
                        version=${{ inputs.version }}\
                        architecture=${{ inputs.architecture }} \
                        vmSize=${{ inputs.vmSize }}